apiVersion: v1
kind: Service
metadata:
  name: master # Name of the external-facing service
  namespace: simulator # Namespace where the service is deployed
  labels:
    app: master # Label to identify the service
spec:
  selector:
    app: master # Selects pods with this label
  type: LoadBalancer # Exposes the service externally via a LoadBalancer
  ports:
    - port: 8089  # External port exposed by the LoadBalancer
      targetPort: 8089 # Port inside the container that receives traffic

---
apiVersion: v1
kind: Service
metadata:
  name: master-internal # Internal service for inter-pod communication
  namespace: simulator # Namespace where the service is deployed
  labels:
    app: master # Label to identify the service
spec:
  selector:
    app: master # Selects pods with this label
  type: ClusterIP # Internal-only service, not exposed externally
  ports:
    - port: 5557 # Internal communication port for Locust workers
      targetPort: 5557 # Port inside the container that receives traffic

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: master # Name of the deployment
  namespace: simulator # Namespace where the deployment is created
  labels:
    app: master # Label to identify the deployment
spec:
  replicas: 1 # Only one master instance is deployed
  selector:
    matchLabels:
      app: master # Matches pods with this label
  strategy:
    type: Recreate # Ensures existing pods are terminated before new ones are created
  template:
    metadata:
      labels:
        app: master # Label assigned to pods created by this deployment
    spec:
      containers:
        - name: master # Container name
          # ✅ Replace this image with the one built using the provided Dockerfile.
          image: my-account/simulator:latest # Image used for the simulator master
          imagePullPolicy: "Always" # Always pull the latest image (useful for debugging)
          env: # Environment variables for PostgreSQL connection
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_HOST
              value: "db-internal.analysis"
          command:
            [
              "locust",
              "-f",
              "locustfile.py", # Load testing script
              "--master", # Runs as a Locust master node
              "-H",
              "http://producer.producer:8080", # Target service for load testing
            ]
          ports:
            - containerPort: 8089 # Port for the Locust web UI
            - containerPort: 5557 # Port for Locust worker communication
          resources: # Resource limits for the container
            limits:
              cpu: 1000m # Maximum CPU allocation (1 vCPU)
              memory: 1024Mi # Maximum memory allocation (1GB)
