apiVersion: v1
kind: Service
metadata:
  name: worker # Name of the service
  namespace: simulator # Namespace where the service is deployed
  labels:
    app: worker # Label to identify the service
spec:
  selector:
    app: worker # Selects pods with this label
  type: ClusterIP # Internal-only service, not exposed externally
  ports:
    - port: 8089 # Internal port for Locust workers
      targetPort: 8089 # Port inside the container that receives traffic

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker # Name of the deployment
  namespace: simulator # Namespace where the deployment is created
  labels:
    app: worker # Label to identify the deployment
spec:
  replicas: 6 # Deploys 6 replicas of the worker nodes
  selector:
    matchLabels:
      app: worker # Matches pods with this label
  strategy:
    type: Recreate # Ensures existing pods are terminated before new ones are created
  template:
    metadata:
      labels:
        app: worker # Label assigned to pods created by this deployment
    spec:
      containers:
        - name: worker # Container name
          # ✅ Replace this image with the one built using the provided Dockerfile.
          image: my-account/simulator:latest # Image used for the simulator worker
          imagePullPolicy: "Always" # Always pull the latest image (useful for debugging)
          command: # Command to run Locust as a worker node
            [
              "locust",
              "-f",
              "locustfile.py", # Load testing script
              "--worker", # Runs as a Locust worker node
              "--master-host",
              "master-internal", # Connects to the Locust master service
            ]
          env: # Environment variables for PostgreSQL and test configurations
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_HOST
              value: "db-internal.analysis" # Internal PostgreSQL service hostname
            - name: SEGMENT_SIZE
              value: "5000" # Defines the segment size for the test
          resources: # Resource limits for the container
            limits:
              cpu: 1000m # Maximum CPU allocation (1 vCPU)
              memory: 2048Mi # Maximum memory allocation (2GB)
