{
 "title": "Kafka Producer Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<h2><center>Buffer 구간</center></h2>"
  },
  {
   "title": "Compression Rate",
   "type": "graph",
   "description": "프로듀서 레코드 압축률",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_compression_rate_avg",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Waiting Threads",
   "type": "graph",
   "description": "대기 중인 쓰레드",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kafka_producer_waiting_threads", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Buffer Available Size(bytes)",
   "type": "graph",
   "description": "가용한 버퍼 사이즈",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_buffer_available_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bufferpool Wait Ratio",
   "type": "graph",
   "description": "Buffer pool에 데이터를 추가하기 위해 대기한 시간의 비율",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_bufferpool_wait_ratio",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IO Wait Time(ns)",
   "type": "graph",
   "description": "CPU가 I/O 작업 완료까지 기다리(idle) 평균 시간",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_io_wait_time_ns_avg",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Record Queue Waiting Average Time(ms)",
   "type": "graph",
   "description": "프로듀서가 레코드큐에 대기하는 평균 시간(ms)",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_record_queue_time_avg",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 18 },
   "content": "<h2><center>Sender 구간</center></h2>"
  },
  {
   "title": "Connection Count",
   "type": "graph",
   "description": "브로커와 커넥션 수",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_connection_count",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Select Rate",
   "type": "graph",
   "description": "브로커가 전송할 데이터가 있는지 확인한 횟수",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kafka_producer_select_rate", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Record Error Rate",
   "type": "graph",
   "description": "레코드 전송 실패 비율",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_record_error_rate",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 28 },
   "content": "<h2><center>Broker 전송 구간</center></h2>"
  },
  {
   "title": "Record Send Rate",
   "type": "graph",
   "description": "초당 전송되는 레코드 수",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_record_send_rate",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(kafka_producer_record_send_rate)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Outgoing Record bytes",
   "type": "graph",
   "description": "초당 전송되는 레코드 사이즈",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_producer_node_outgoing_byte_rate)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "graph",
   "description": "요청 후 응답받는 평균 시간",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_node_request_latency_avg",
     "legendFormat": "{{node_id}}"
    }
   ]
  }
 ]
}